### ISSUE TITLE
エブリスタの小説を取り込んだ際、改行が消えてしまう

### ISSUE THREAD

**Issue by LazyGon** [limura/NovelSpeaker#119]
環境は以下の通りです。
* iPhone8
* iOS 13.3.1
* ことせかい 1.1.67（多分

エブリスタの小説を「共有→ことせかいへ取り込む」から取り込んだのですが、改行が読み込まれるところと読み込まれないところが出てきてしまいました。
場合によってはあるはずの改行が全て潰れてしまうものもあるようです。

以下の文章は、ﾋｨｯﾂｶﾗﾙﾄﾞ様の「ハクスラ異世界に転生したから、ひたすらレベル上げをしながらマジックアイテムを掘りまくって、飽きたら拾ったマジックアイテムで色々と遊んでみる物語。」という作品の[2ページ目](https://estar.jp/novels/25573536/viewer?page=2)を取り込んだ結果です。

俺は平凡な高校生だった。 それが今は闇の中に居る。 『はぁ～い、私は異世界転生係の女神様ですよ～』 唐突だな……。 それにしても、何とも軽い女神様が出てきたもんだ……。 ハズレかな？ 『なんとでもいいなさい。後がつっかえているから、ちゃちゃっと話を進めるわよ～』 あ、はい。どうぞ……。 『まず、最初に教えておきますが、貴方は死にましたから異世界に転生されます。いいですね』 ざっくりとした説明だな、この女神様は……。 で、何で俺は死んだのですか？ 『そんなことどうでもいいでしょう。どうせ生き返らないし、元の世界には戻れないのだから。それより転生の話を進めますね』 うわぁ……。そのぐらい教えてくれよ……。 『えーと、貴方が転生される世界は──』 無視かよ……。 『ファンタジーの世界です、ラッキー♡』 ラッキー♡、じゃあねえよ。俺は何で、死・ん・だ・ん・だ・よ！？ 『それで～、転生したらチートっぽい強さを獲得できますので、好きに生きてくださいね』 うわ、人の話を完全に聞いてねえよ、この女神様はよ！ でも、チート能力はありがたいな。 『チート無双なので、勇者に成るもよし、魔王になるもよしですからね。わーい、やったね♡』 やったね♡、じゃねーよ。 なんなんだ、この女神様は……。 『貴方が貰えるチートスキルは、鍛えれば無限に強く成れる(レベルアップする)スキルと、わんさかとマジックアイテムを拾える(掘れる)スキルです。やったね♡』

いちいち語尾にハートマーク付けるなよ。うぜーよ、マジで。

『もう、さっきから生意気ばかり言ってるとペナルティーを付けちゃうぞ、ぷんぷん！』

ぷんぷんって……。ごめんなさい……。

俺の第二の人生は、楽で怠惰な生活を送れるように宜しくお願いいたします、美しい女神様！

『だめー、今さら媚びを売っても遅いんだから。もう決めちゃったもんね～』

なに！？

『女神から、貴方にペナルティーを授けます！』

ちょっと待ってくれ、本当にご免なさい！！

『ど、れ、に、し、よ、う、か、な、め、が、み、さ、ま、の、ゆ、う、と、お、り～』

あんた適当に選んでるな！

『よ～し、これに決めましたわ～』

いーやー、本当にペナルティーなんて止(や)めてください！

『貴方には、エロイことをすると死んじゃうペナルティーを与えますからね。いえーい♡』

いえーい♡、じゃねえよ！

なんだよ、それ！？

『じゃあ、異世界に転生させますね、頑張ってね～♡』

ちょ、ちょっと待てよ！

最後までちゃんと説明しろや！

殆ど説明が無いじゃんか！

ジェットコースターかよ！

『飛んでけー♡』

飛んでけー♡、じゃねえわ！！

『ばいばーい♡』

うわぁぁぁああああ！！！

そして、俺が次に気が付いた時には、見慣れない草原のド真ん中に立って居た。

しかも、全裸で……。

服ぐらい初期アイテムで支給しやがれよ……。

糞女神が……。

【つづく】

**Comment by limura** [comment]
IceCream ブランチ のものを Version 2.0.0 としてリリースしましたのでこの issue は close します。
