### ISSUE TITLE
ルビを読み上げない事がある

### ISSUE THREAD

**Issue by limura** [limura/NovelSpeaker#87]
ご意見ご要望フォームより。

本文
>  speech ruby only is requring deactivate and reactivate to work at each chapter I read

機械翻訳

> 私が読んだ各章で働くためには、音声ルビーのみが非活性化と再起動が必要です

ざっと確認した所では再現できず。要調査。

**Comment by MurtadhaQahtan** [comment]
私は英語があまりよくないので、事前に不便な点をお詫びします。
音声ルビーのみの機能は、起動時に正常に機能していますが、小説が次の章に進むと、機能が停止し、再び機能させるためには、再び無効にして再度アクティブにする必要があります

**Comment by limura** [comment]
再度手元の端末で試してみたのですが、再現しませんでした。
手順としては以下のようにやりました。

1. 「新規自作小説の追加」で自作小説を追加
2. (全ての章で)ルビ表記を含む文章を5章分程作成
3. 1章目の最初から読み上げを開始して最終章まで読み上げるのを聞く

この 3. の手順にて動作を確認していますが、

- 表示したままでの再生
- 電源ボタンを押してバックグラウンド再生にした状態

の二種類の手法でやっても再現はしませんでした。

確実に再現可能な方法はありますでしょうか？

**Comment by limura** [comment]
a88d883
の修正で、この問題の少なくとも1つが修正されます。
他にも似たような結果になる問題があれば駄目ですけれども……

この修正を施したものでAppleへの提出作業に入りますのでアップデートをお待ち下さい。

**Comment by limura** [comment]
上記の修正を施されたものがリリースされましたのでcloseします。
